package com.example.paymentservice.enums;


public enum FailureCode {
    INVALID_REQUEST,
    INSUFFICIENT_BALANCE,
    FRAUD_REJECTED,
    WALLET_DEBIT_FAILED,
    PAYMENT_NOT_FOUND,
    RETRY_NOT_ALLOWED,
    INTERNAL_ERROR,
    WALLET_SERVICE_TIMEOUT,
    LEDGER_WRITE_FAILED,
    FRAUD_SERVICE_TIMEOUT
}
