CREATE TABLE payments (
                          payment_id VARCHAR(50) PRIMARY KEY,
                          customer_id VARCHAR(50) NOT NULL,
                          merchant_id VARCHAR(50) NOT NULL,
                          wallet_id VARCHAR(50) NOT NULL,
                          amount DECIMAL(18,2) NOT NULL,
                          currency VARCHAR(10) NOT NULL,
                          payment_method VARCHAR(20) NOT NULL,
                          status VARCHAR(20) NOT NULL,
                          transaction_id VARCHAR(50),
                          idempotency_key VARCHAR(100) NOT NULL UNIQUE,
                          request_hash VARCHAR(255),
                          failure_code VARCHAR(50),
                          failure_reason VARCHAR(255),
                          created_at TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP NOT NULL,
                          version INT DEFAULT 0
);

CREATE TABLE payment_status_history (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        payment_id VARCHAR(50) NOT NULL,
                                        old_status VARCHAR(20),
                                        new_status VARCHAR(20) NOT NULL,
                                        reason_code VARCHAR(50),
                                        reason_message VARCHAR(255),
                                        changed_at TIMESTAMP NOT NULL
);